rules = [
  (r'\"\"\"', 'TRIPLEQUOTE'),
  (r'\'\'\'', 'TRIPLEQUOTE'),
  (r'from\s', 'FROM'),
  (r'import\s', 'IMPORT'),
  (r'as\s', 'AS'),
  (r'class\s', 'CLASS'),
  (r'def\s', 'DEF'),
  (r'pass', 'PASS'),
  (r'return\s', 'RETURN'),
  (r'continue\n', 'CONTINUE'),
  (r'break\w', 'BREAK ERR'),
  (r'break\n', 'BREAK NEWLINE'),
  (r'if\s', 'IF'),
  (r'if\(', 'IF LPAREN'),
  (r'elif', 'ELIF'),
  (r'elif\(', 'ELIF LPAREN'),
  (r'else', 'ELSE'),
  (r'for\s', 'FOR'),
  (r'in\s', 'IN'),
  (r'while', 'WHILE'),
  (r'None', 'NONE'),
  (r'True', 'TRUE'),
  (r'False', 'FALSE'),
  (r'not', 'NOT'),
  (r'and', 'AND'),
  (r'\sor\s', 'OR'),
  (r'is\s', 'IS'),
  (r'print', 'PRINT'),
  (r'bool', 'BOOL'),
  (r'abs', 'ABS'),
  (r'round', 'ROUND'),
  (r'pow', 'POW'),
  (r'\".*\"', 'STRING'),
  (r'\'.*\'', 'STRING'),
  (r'\.', 'WITH_METHOD'),
  (r':', 'COLON'),
  (r';', 'SEMICOLON'),
  (r'\n', 'NEWLINE'),
  (r'\s', 'WHITESPACE'),
  (r'\d+', 'NUMBER'),
  (r'\d+.+\d', 'FLOAT'),
  (r'[a-zA-Z_]+[\da-zA-Z_0-9]*', 'IDENTIFIER'),
  (r'\+', 'PLUS'),
  (r'\-', 'MINUS'),
  (r'\*', 'MUL'),
  (r'\/', 'DIV'),
  (r'\%', 'MOD'),
  (r'\(', 'LPAREN'),
  (r'\)', 'RPAREN'),
  (r'\[', 'LBRACKET'),
  (r'\]', 'RBRACKET'),
  (r'==', 'DOUBLE_EQUAL'),
  (r'=', 'EQUAL'),
  (r'!=', 'NOT_EQUAL'),
  (r'>=', 'GREATER_OR_EQUAL_THAN'),
  (r'>', 'GREATER_THAN'),
  (r'<=', 'LESS_OR_EQUAL_THAN'),
  (r'<', 'LESS_THAN'),
  (r'\w', 'NULL'),
]